USE [master]
GO

/****** Object:  Database [TMG]    Script Date: 08/02/2014 04:15:37 ******/
CREATE DATABASE [TMG] ON  PRIMARY 
( NAME = N'TMG', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TMG.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TMG_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\TMG_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TMG] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TMG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TMG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TMG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TMG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TMG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TMG] SET ARITHABORT OFF 
GO

ALTER DATABASE [TMG] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TMG] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TMG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TMG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TMG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TMG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TMG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TMG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TMG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TMG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TMG] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TMG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TMG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TMG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TMG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TMG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TMG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TMG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TMG] SET  READ_WRITE 
GO

ALTER DATABASE [TMG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TMG] SET  MULTI_USER 
GO

ALTER DATABASE [TMG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TMG] SET DB_CHAINING OFF 
GO

