//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TMG.DataExtractor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TMGEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TMGEntities object using the connection string found in the 'TMGEntities' section of the application configuration file.
        /// </summary>
        public TMGEntities() : base("name=TMGEntities", "TMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TMGEntities object.
        /// </summary>
        public TMGEntities(string connectionString) : base(connectionString, "TMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TMGEntities object.
        /// </summary>
        public TMGEntities(EntityConnection connection) : base(connection, "TMGEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TMGModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="pER_NO">Initial value of the PER_NO property.</param>
        /// <param name="lAST_EDIT">Initial value of the LAST_EDIT property.</param>
        /// <param name="dSID">Initial value of the DSID property.</param>
        /// <param name="sEX">Initial value of the SEX property.</param>
        /// <param name="lIVING">Initial value of the LIVING property.</param>
        /// <param name="bIRTHORDER">Initial value of the BIRTHORDER property.</param>
        /// <param name="mULTIBIRTH">Initial value of the MULTIBIRTH property.</param>
        /// <param name="aDOPTED">Initial value of the ADOPTED property.</param>
        /// <param name="aNCE_INT">Initial value of the ANCE_INT property.</param>
        /// <param name="dESC_INT">Initial value of the DESC_INT property.</param>
        public static Person CreatePerson(global::System.Int64 pER_NO, global::System.DateTime lAST_EDIT, global::System.Int64 dSID, global::System.String sEX, global::System.String lIVING, global::System.String bIRTHORDER, global::System.String mULTIBIRTH, global::System.String aDOPTED, global::System.String aNCE_INT, global::System.String dESC_INT)
        {
            Person person = new Person();
            person.PER_NO = pER_NO;
            person.LAST_EDIT = lAST_EDIT;
            person.DSID = dSID;
            person.SEX = sEX;
            person.LIVING = lIVING;
            person.BIRTHORDER = bIRTHORDER;
            person.MULTIBIRTH = mULTIBIRTH;
            person.ADOPTED = aDOPTED;
            person.ANCE_INT = aNCE_INT;
            person.DESC_INT = dESC_INT;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PER_NO
        {
            get
            {
                return _PER_NO;
            }
            set
            {
                if (_PER_NO != value)
                {
                    OnPER_NOChanging(value);
                    ReportPropertyChanging("PER_NO");
                    _PER_NO = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PER_NO");
                    OnPER_NOChanged();
                }
            }
        }
        private global::System.Int64 _PER_NO;
        partial void OnPER_NOChanging(global::System.Int64 value);
        partial void OnPER_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FATHER
        {
            get
            {
                return _FATHER;
            }
            set
            {
                OnFATHERChanging(value);
                ReportPropertyChanging("FATHER");
                _FATHER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FATHER");
                OnFATHERChanged();
            }
        }
        private Nullable<global::System.Int64> _FATHER;
        partial void OnFATHERChanging(Nullable<global::System.Int64> value);
        partial void OnFATHERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MOTHER
        {
            get
            {
                return _MOTHER;
            }
            set
            {
                OnMOTHERChanging(value);
                ReportPropertyChanging("MOTHER");
                _MOTHER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MOTHER");
                OnMOTHERChanged();
            }
        }
        private Nullable<global::System.Int64> _MOTHER;
        partial void OnMOTHERChanging(Nullable<global::System.Int64> value);
        partial void OnMOTHERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LAST_EDIT
        {
            get
            {
                return _LAST_EDIT;
            }
            set
            {
                OnLAST_EDITChanging(value);
                ReportPropertyChanging("LAST_EDIT");
                _LAST_EDIT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LAST_EDIT");
                OnLAST_EDITChanged();
            }
        }
        private global::System.DateTime _LAST_EDIT;
        partial void OnLAST_EDITChanging(global::System.DateTime value);
        partial void OnLAST_EDITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DSID
        {
            get
            {
                return _DSID;
            }
            set
            {
                OnDSIDChanging(value);
                ReportPropertyChanging("DSID");
                _DSID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DSID");
                OnDSIDChanged();
            }
        }
        private global::System.Int64 _DSID;
        partial void OnDSIDChanging(global::System.Int64 value);
        partial void OnDSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> REF_ID
        {
            get
            {
                return _REF_ID;
            }
            set
            {
                OnREF_IDChanging(value);
                ReportPropertyChanging("REF_ID");
                _REF_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REF_ID");
                OnREF_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _REF_ID;
        partial void OnREF_IDChanging(Nullable<global::System.Int64> value);
        partial void OnREF_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REFERENCE
        {
            get
            {
                return _REFERENCE;
            }
            set
            {
                OnREFERENCEChanging(value);
                ReportPropertyChanging("REFERENCE");
                _REFERENCE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REFERENCE");
                OnREFERENCEChanged();
            }
        }
        private global::System.String _REFERENCE;
        partial void OnREFERENCEChanging(global::System.String value);
        partial void OnREFERENCEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SPOULAST
        {
            get
            {
                return _SPOULAST;
            }
            set
            {
                OnSPOULASTChanging(value);
                ReportPropertyChanging("SPOULAST");
                _SPOULAST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SPOULAST");
                OnSPOULASTChanged();
            }
        }
        private Nullable<global::System.Int64> _SPOULAST;
        partial void OnSPOULASTChanging(Nullable<global::System.Int64> value);
        partial void OnSPOULASTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SCBUFF
        {
            get
            {
                return _SCBUFF;
            }
            set
            {
                OnSCBUFFChanging(value);
                ReportPropertyChanging("SCBUFF");
                _SCBUFF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SCBUFF");
                OnSCBUFFChanged();
            }
        }
        private global::System.String _SCBUFF;
        partial void OnSCBUFFChanging(global::System.String value);
        partial void OnSCBUFFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PBIRTH
        {
            get
            {
                return _PBIRTH;
            }
            set
            {
                OnPBIRTHChanging(value);
                ReportPropertyChanging("PBIRTH");
                _PBIRTH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PBIRTH");
                OnPBIRTHChanged();
            }
        }
        private global::System.String _PBIRTH;
        partial void OnPBIRTHChanging(global::System.String value);
        partial void OnPBIRTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PDEATH
        {
            get
            {
                return _PDEATH;
            }
            set
            {
                OnPDEATHChanging(value);
                ReportPropertyChanging("PDEATH");
                _PDEATH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PDEATH");
                OnPDEATHChanged();
            }
        }
        private global::System.String _PDEATH;
        partial void OnPDEATHChanging(global::System.String value);
        partial void OnPDEATHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SEX
        {
            get
            {
                return _SEX;
            }
            set
            {
                OnSEXChanging(value);
                ReportPropertyChanging("SEX");
                _SEX = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SEX");
                OnSEXChanged();
            }
        }
        private global::System.String _SEX;
        partial void OnSEXChanging(global::System.String value);
        partial void OnSEXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LIVING
        {
            get
            {
                return _LIVING;
            }
            set
            {
                OnLIVINGChanging(value);
                ReportPropertyChanging("LIVING");
                _LIVING = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LIVING");
                OnLIVINGChanged();
            }
        }
        private global::System.String _LIVING;
        partial void OnLIVINGChanging(global::System.String value);
        partial void OnLIVINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BIRTHORDER
        {
            get
            {
                return _BIRTHORDER;
            }
            set
            {
                OnBIRTHORDERChanging(value);
                ReportPropertyChanging("BIRTHORDER");
                _BIRTHORDER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BIRTHORDER");
                OnBIRTHORDERChanged();
            }
        }
        private global::System.String _BIRTHORDER;
        partial void OnBIRTHORDERChanging(global::System.String value);
        partial void OnBIRTHORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MULTIBIRTH
        {
            get
            {
                return _MULTIBIRTH;
            }
            set
            {
                OnMULTIBIRTHChanging(value);
                ReportPropertyChanging("MULTIBIRTH");
                _MULTIBIRTH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MULTIBIRTH");
                OnMULTIBIRTHChanged();
            }
        }
        private global::System.String _MULTIBIRTH;
        partial void OnMULTIBIRTHChanging(global::System.String value);
        partial void OnMULTIBIRTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ADOPTED
        {
            get
            {
                return _ADOPTED;
            }
            set
            {
                OnADOPTEDChanging(value);
                ReportPropertyChanging("ADOPTED");
                _ADOPTED = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ADOPTED");
                OnADOPTEDChanged();
            }
        }
        private global::System.String _ADOPTED;
        partial void OnADOPTEDChanging(global::System.String value);
        partial void OnADOPTEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ANCE_INT
        {
            get
            {
                return _ANCE_INT;
            }
            set
            {
                OnANCE_INTChanging(value);
                ReportPropertyChanging("ANCE_INT");
                _ANCE_INT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ANCE_INT");
                OnANCE_INTChanged();
            }
        }
        private global::System.String _ANCE_INT;
        partial void OnANCE_INTChanging(global::System.String value);
        partial void OnANCE_INTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DESC_INT
        {
            get
            {
                return _DESC_INT;
            }
            set
            {
                OnDESC_INTChanging(value);
                ReportPropertyChanging("DESC_INT");
                _DESC_INT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DESC_INT");
                OnDESC_INTChanged();
            }
        }
        private global::System.String _DESC_INT;
        partial void OnDESC_INTChanging(global::System.String value);
        partial void OnDESC_INTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RELATE
        {
            get
            {
                return _RELATE;
            }
            set
            {
                OnRELATEChanging(value);
                ReportPropertyChanging("RELATE");
                _RELATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RELATE");
                OnRELATEChanged();
            }
        }
        private Nullable<global::System.Int64> _RELATE;
        partial void OnRELATEChanging(Nullable<global::System.Int64> value);
        partial void OnRELATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RELATEFO
        {
            get
            {
                return _RELATEFO;
            }
            set
            {
                OnRELATEFOChanging(value);
                ReportPropertyChanging("RELATEFO");
                _RELATEFO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RELATEFO");
                OnRELATEFOChanged();
            }
        }
        private Nullable<global::System.Int64> _RELATEFO;
        partial void OnRELATEFOChanging(Nullable<global::System.Int64> value);
        partial void OnRELATEFOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TT
        {
            get
            {
                return _TT;
            }
            set
            {
                OnTTChanging(value);
                ReportPropertyChanging("TT");
                _TT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TT");
                OnTTChanged();
            }
        }
        private global::System.String _TT;
        partial void OnTTChanging(global::System.String value);
        partial void OnTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FLAG1
        {
            get
            {
                return _FLAG1;
            }
            set
            {
                OnFLAG1Changing(value);
                ReportPropertyChanging("FLAG1");
                _FLAG1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FLAG1");
                OnFLAG1Changed();
            }
        }
        private global::System.String _FLAG1;
        partial void OnFLAG1Changing(global::System.String value);
        partial void OnFLAG1Changed();

        #endregion
    
    }

    #endregion
    
}
